title: Lorentiz Invariance Violation 
description: We search Lorentiz Invariance Violation process in quark sector with the LHC luminocity measured by the ATLAS detector.
show_downloads: false
google_analytics:

theme: jekyll-theme-tactile

