
title: Lorentiz invariance violation process at the LHC
description: We search Lorentiz Invariance Violation process in quark sector with the LHC luminocity measured by the ATLAS detector.

#theme: jekyll-theme-tactile
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme
